find_package(GTest REQUIRED)
include(romea_add_gtest)

romea_add_gtest(test_filter test_filter.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_unscented_transform test_unscented_transform.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_kalman_filter test_kalman_filter.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_gaussian_types test_gaussian_types.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_kalman_equations test_kalman_equations.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_particle_filter test_particle_filter.cpp LIBRARIES ${PROJECT_NAME})
romea_add_gtest(test_filter_base test_filter_base.cpp LIBRARIES ${PROJECT_NAME})
